### ISSUE TITLE
프로젝트 환경셋팅 및 그리드 설정

### ISSUE THREAD

**Issue by leejiwonn** [Matching42/Matching42-front#1]
### Description
- 프로젝트 환경셋팅 및 그리드 설정 (레이아웃의 기본이 되는 컴포넌트 생성)

### TODO List
- [x] `CRA(Create-React-App)` 사용한 환경셋팅
- [x] `ESLint` , `Prettier` 적용 후, 설정 파일 작성
- [x] 메인 화면 그리드 형태에 따른 주요 컴포넌트 생성
- [x] `axios` , `SWR` 을 사용한 데이터 연동 예시 작성
