### ISSUE TITLE
해상도 높을 때 CSS 수정, totalSize, tags API 연동

### ISSUE THREAD

**Issue by deathnet** [Matching42/Matching42-front#108]
### Todo
- [x] 유저 이미지 찌그러지는 문제
- [x] totalSize, tags API 연동
- [x] 해상도 높을 때 wait과 subject Y축이 다름
- [x] 해상도 높을 대 스터디 종료 모달 css 수정
