### ISSUE TITLE
Main Page - ProfileView 컴포넌트 구현

### ISSUE THREAD

**Issue by from97** [Matching42/Matching42-front#11]
## Description
Main 페이지의 ProfileView 컴포넌트 UI 구현하기 

### Todo
- [x] Profile title 구현
- [x] Profile description 구현
- [x] Profile - user info list 구현
- [x] ProfileView 컴포넌트 세부 스타일 수정
- [x] Profile description line-height 스타일 속성 관련 문제 해결
- [x] CSS line-height 유동적인 값으로 변경 (ex 1.5)
- [x] Prettier 적용 코드 정렬
- [x] Props 받아오는 부분 구현 (dummy data 사용)

**Comment by from97** [comment]
## Description
Main Page의 ProfileView 컴포넌트 세부 스타일 수정 (Adobe XD 접근권한 부여 완료로 디자인 시안의 세부 스타일-폰트 사이즈 등- 확인이 가능해져서, 임의로 설정했던 세부 스타일을 정확하게 재설정함). 

### Todo
- [ ] ProfileView 컴포넌트 세부 스타일 수정

**Comment by from97** [comment]
+) PR 피드백받은 부분 수정 (부모 요소가 %인 상태에서 line-height를 px로 설정해 overflow 발생할 수 있다는 피드백 있었음)

**Comment by from97** [comment]
CSS line-height 유동적인 값으로 변경 (ex 1.5), Prettier 적용 코드 정렬, Props 받아오는 부분 구현 (dummy data 사용) 진행

**Comment by seo2im** [comment]
제가 정리하다가 해당 연결 PR을 merge하였습니다. 아직 작업 못한 사항에 대해 새 PR로  작업해주시기 바랍니다.
(롤백보다 새로 파는게 나아 보입니다)

**Comment by from97** [comment]
> 제가 정리하다가 해당 연결 PR을 merge하였습니다. 아직 작업 못한 사항에 대해 새 PR로 작업해주시기 바랍니다.
> (롤백보다 새로 파는게 나아 보입니다)

네 알겠습니다
