### ISSUE TITLE
팀 태그 등록 시 잘못된 태그 등록 막기

### ISSUE THREAD

**Issue by from97** [Matching42/Matching42-front#116]
## Description
팀 태그 등록 시, 잘못된 태그(공백 포함 태그, 중복 태그) 등록 막기

### Todo
- [x] 공백 태그 등록 되지 않게 막기
- [x] 공백 포함 태그 등록 막기
- [x] 중복 태그 등록 막기
