### ISSUE TITLE
팀이 종료된 상태일 때, 스터디 종료 버튼 없애고 자물쇠 비활성화 적용

### ISSUE THREAD

**Issue by leejiwonn** [Matching42/Matching42-front#126]
## Description
- 팀이 종료된 상태일 때, 스터디 종료 버튼을 없애고 자물쇠 버튼 또한 비활성화로 표시합니다.
- 나의 팀 목록에서도 종료된 팀은 `END` 로 표시합니다.

### Todo
- [x] 스터디 종료 버튼 감추기
- [x] 자물쇠 버튼 비활성화
- [x] 팀 목록에서 종료된 팀은 `END` 로 표시
