### ISSUE TITLE
팀장이 아닐 때 자물쇠 처리, My Team 없을 때 로딩 처리

### ISSUE THREAD

**Issue by deathnet** [Matching42/Matching42-front#127]
## Description
자물쇠 버튼도 팀장이 아닐 때 회색 처리, 커서 없애기
### Todo
- [x] 팀장 아닐 때 자물쇠 회색 처리
- [x] 팀장 아닐 때 자물쇠 커서 없애기
- [x] My Team 없을 때 더 이상 로딩이 돌지 않도록 수정
- [x] 팀 리스트에서 시간 지나니까 갑자기 팀이 더 보임?
