### ISSUE TITLE
에러 처리

### ISSUE THREAD

**Issue by deathnet** [Matching42/Matching42-front#149]
## Description
에러 상황 관련 동작 확인

### Todo
- [x] 에러 상황 관련 동작 확인
- [x] 에러 상황에 토스트 팝업 띄우기
- [x] SWR 에러 발생시 에러 페이지 렌더링
