### ISSUE TITLE
2차 반응형 대응 & 팀 워크스페이스 링크 새 탭으로 오픈

### ISSUE THREAD

**Issue by leejiwonn** [Matching42/Matching42-front#158]
## Description
- 1차 대응 때 놓친 부분 디벨롭합니다. 
- 팀 워크스페이스 링크 클릭 시 새 탭으로 열리도록 수정합니다.

### Todo
- [x] 팀 수정 아이콘 크기 조정
- [x] 팀 수정 폼 로고 크기 조정
- [x] empty 이미지 크기 조정
- [x] 팀 리스트 없을 때 글자 크기 조정
- [x] 팀 워크스페이스 링크 클릭 시 새 탭으로 열기
