### ISSUE TITLE
Main Page - MatchingStateView 컴포넌트 구현

### ISSUE THREAD

**Issue by from97** [Matching42/Matching42-front#18]
## Description
Main Page의 MatchingStateView 컴포넌트 형태 구현

### Todo
- [x] matching state descrption 구현 및 배치
- [x] matching start button 구현 및 배치
- [x] matchingStateView default props 정의
- [x] matchingStateView 컴포넌트에서 default props 사용
- [x] props destructuring으로 받아오기

**Comment by from97** [comment]
props destructuring으로 받아오기

**Comment by from97** [comment]
props destructuring으로 받아오기

**Comment by from97** [comment]
prettier 적용을 위해 이슈 오픈
