### ISSUE TITLE
매칭 완료된 유저의 ProfileView description 변경

### ISSUE THREAD

**Issue by from97** [Matching42/Matching42-front#182]
## Description
매칭 완료된 유저의 Main Page > ProfileView의 description 문구 변경

매칭 신청 전 : 오늘 하루도 힘차게 달려볼까요?
오른쪽 상단의 매칭 신청하기 버튼을 눌러 시작해보세요!

매칭 신청 후 : 매칭 신청이 완료되었어요😃 팀원을 찾을 때까지 조금만 기다려주세요! 

매칭 완료 후 : 오늘도 Matching42와 함께 즐겁게 동료학습해요! 

문구 추천 받습니당

### Todo
- [ ] 매칭 신청 전 : waitlist에 없는 경우, team에 속해있지 않은 경우
- [ ] 매칭 신청 후 : waitlist에 있는 경우, team에 속해있지 않은 경우
- [ ] 매칭 완료 후 : waitlist에 없는 경우, team에 속해있는 경우
