### ISSUE TITLE
프로젝트 배포 및 배포 자동화 설정

### ISSUE THREAD

**Issue by leejiwonn** [Matching42/Matching42-front#24]
## Description
- Github Pages 사용해서 프로젝트를 배포하고, Github Action 으로 CI/CD 환경을 구축합니다.

### Todo
- [x] `gh-pages` 패키지 설치 후 정상적으로 배포되도록 설정 (배포 브랜치는 `deploy`)
- Github Action 활용하여 CI/CD 환경 구축 (`main` 에서 `deploy` 로  할 경우)
  - [x] `main` 에서 `deploy` 브랜치로 PR 을 날렸을 때, `ESLint` 및 `build` 검사 → 실패 시, `merge` 방지
  - [x] `deploy` 브랜치로 PR 을 `merge` 하거나 `push` 했을 때, 자동으로 배포
