### ISSUE TITLE
Detail Page > TeamProfileView 컴포넌트 다이어그램 작성

### ISSUE THREAD

**Issue by from97** [Matching42/Matching42-front#39]
## Description
Detail Page의 TeamProfileView 컴포넌트 다이어그램 작성하기

### Todo
- [x] TeamProfileView 컴포넌트 다이어그램 작성
- [x] TeamProfileView 컴포넌트 구조 작성
- [x] TeamProfileView 요구 데이터 작성

#### 다이어그램
https://www.figma.com/file/cuPZrge865KC09VZLlxreB/42Matching?node-id=474%3A343

#### 컴포넌트 구조
```jsx
<TeamProfileViewStyled>
	<TeamProfile>
		<TeamProfile.Name />
		<TeamProfile.EditButton />
		<TeamProfile.Dday />
	</TeamProfile>
	<TeamDescription />
	<TeamTagList>
		<TeamTagList.Item>
	</TeamTagList>
</TeamProfileViewStyled>
```

#### 요구 데이터
- Team.teamName: TeamName 컴포넌트에서 사용. EditTeamNameButton 컴포넌트에서 수정가능해야 함. 
- Team.startDate: TeamDday 컴포넌트에서 사용. 현재 Date - start Date 계산 결과를 일수로 표시. (`D-{nowDate - startDate}+`) (ex: D-30+)

**Comment by from97** [comment]
TeamProfile 컴포넌트 디자인이 변경되어, 변경된 디자인에 따라 다이어그램, 흐름도 등을 수정하기 위해 이슈 다시 오픈합니다

**Comment by from97** [comment]
TeamProfileView 컴포넌트 디자인 수정 사항 반영해 컴포넌트 구조 수정함

**Comment by from97** [comment]
TeamProfileView 컴포넌트 디자인 수정 사항 반영해 컴포넌트 다이어그램 수정 완료
