### ISSUE TITLE
프로젝트 Git 세팅

### ISSUE THREAD

**Issue by seo2im** [Matching42/Matching42-front#6]
## Description
워크플로우 가이드에 맞추어 github setting 변경

## Todo
- [x] 이슈 라벨 설정
- [x] 이슈 마일스톤 등록
- [x] 이슈 template 등록
- [x] commit template 파일 등록
- [x] PR template 적용
- [x] Project auto 설정 세팅
- [x] 1주기 Issue 정리작업
