### ISSUE TITLE
Dropdown 컴포넌트 개선 및 애니메이션 적용

### ISSUE THREAD

**Issue by from97** [Matching42/Matching42-front#61]
## Description
Dropdown 컴포넌트 개선 사항 및 애니메이션 효과 적용

### Todo
- [x] Dropdown 컴포넌트 디폴트 서브젝트(초기 선택값 Libft) 제거
- [x] Dropdown open/close 상태에 따라 "Subject" 색상 및 화살표 방향 변경
- [x] Dropdown 버튼 이름 선택된 서브젝트 이름으로 변경
- [x] Dropdown 내부 스크롤 적용
- [x] Dropdown 컴포넌트에 애니메이션 효과 적용
