### ISSUE TITLE
로그인 연동 및 리다이렉션 적용

### ISSUE THREAD

**Issue by leejiwonn** [Matching42/Matching42-front#80]
## Description
- 로그인 연동 후, 유저 토큰 여부에 따른 리다이렉션을 구현합니다.

### Todo
- [x] 로그인 연동해서 토큰 받아오기
- [x] 토큰 여부에 따른 리다이렉션 -> 로고 클릭했을 때도 동일하게 체크

### More details
- 과도한 리렌더링(깜빡임) 방지 필요
    - [x] `Header` 컴포넌트 공통으로 분리
    - [x] 리렌더링 방지 -> `SWR` 정보 가져올 때 `loading` 하지 않고, `?.` 사용해서 데이터 관리 (데이터 자체가 `null` 일 때만 `loading`)
- [x] 리다이렉션 점검
    - `user` 정보 없을 때 : `login` 으로 리다이렉션, `home` `detail` 접근 불가
    - `user` 정보 있을 때 : `home` 으로 리다이렉션, `detail` 접근 가능, `login` 접근 불가
- [x] `recoil` 덜어내고 `context api` 적용 필요

=> 현재 리다이렉션 시 UI 가 사용자에게 노출되는 현상은 `useLayoutEffect` 로 막아놓음. 추후 리팩토링 시, `showLoading` 같이 전환 또는 로딩할 때 보여줄 임시 화면을 만들면 좋을 것 같음.
=> `token` `user` 정보는 `localStorage` 에 저장하는 방식을 사용함. 토큰 만료 여부를 `user` 로 검사하고 있기 때문에 저장이 불가피함. 나중에 리팩토링 해보면 좋을 것 같음 🥲
