### ISSUE TITLE
TeamList, MyTeamList

### ISSUE THREAD

**Issue by deathnet** [Matching42/Matching42-front#9]
### Todo
- [x] TeamLi(HashTags, TeamImg 포함) 컴포넌트 구현
- [x] TeamList 컴포넌트 구현
- [x] TeamList 컴포넌트 상단의 Wait toggle, Subject dropdown 구현
- [x] MyTeamList 컴포넌트 구현
- [x] 리팩토링

**Comment by seo2im** [comment]
assignee는 해당 이슈의 담당자이므로 본인으로 설정해 주시고 나중에 PR을 생성하실 때 reviewer로 jiwonlee님과 저를 설정해주시면 됩니다. 그리고 Project는 front-project로 설정해 주시고 milstone은 2주기로 설정해 주시기 바랍니다

**Comment by seo2im** [comment]
전통적인 page based pagenation api형태로 구현하겠습니다.
api 형태 /team?page=[number]&limit=[number]

[참고 link](https://velog.io/@leejh3224/%ED%8E%98%EC%9D%B4%EC%A7%80%EB%84%A4%EC%9D%B4%EC%85%98-%EC%BB%A4%EC%84%9C%EA%B8%B0%EB%B0%98-%ED%8E%98%EC%9D%B4%EC%A7%80%EA%B8%B0%EB%B0%98)

더미 mock server 구현 이전까지 이전까지
```javascript
const dummy = Array.from({ length: 100 }).map((_, i) => i)
const sleep = () => {
    return new Promise(resolve => setTimeout(resolve, 1000))
}

export const fetchData = async (page, limit) => {
    await sleep()
    return dummy.slice(page * limit, (page + 1) * limit)
}
```
위 패쳐를 통해 간단히 테스팅을 해보시기 바랍니다(더미 데이터 생성은 힘들것 같으니 위 패쳐로 inifinite scroll을 구현해 보신 후 내부 데이터로 styling 하시길 추천 드립니다

[swr pagination api handling link] (https://swr.vercel.app/docs/pagination)

**Comment by seo2im** [comment]
2개 리뷰 수정사항 확인 부탁드립니다.
resolved: #13
