### ISSUE TITLE
추가 디자인 사항 반영

### ISSUE THREAD

**Issue by leejiwonn** [Matching42/Matching42-front#99]
## Description
- 로딩/에러 페이지 디자인, 매칭 취소 기능 구현, 팀 서브젝트 노출 디자인을 반영합니다.
- 추가적으로 업데이트 된 API 기능을 적용합니다.

### Todo
- [x]  로딩중 or 에러 페이지 디자인 적용
- [x]  매칭 취소 기능 구현
- [x]  팀 서브젝트 노출 디자인 적용
